name: Testing things
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      target:
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout repository to runner
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target }}
